### ISSUE TITLE
[VS2019 Compatibility Issue] Suddenly getting an error after loading solution

### ISSUE THREAD

**Issue by nurbles** [korypostma/BlackSpace#4]
BlackSpace has been working in our VS2019 environment for quite a while, then today we started to see this message pop up shortly after our solution finished loading: 

![BlackSpaceError](https://user-images.githubusercontent.com/14079927/218799432-ab74c4b3-cdb1-4e49-89c8-f9533f9471ce.png)

I've tried waiting several minutes after starting VS2019, but before loading any projects or solutions and the error _does not_ appear.  However, very shortly after the solution finished loading, the error appears.

I suspect an update of some kind, but neither of us is aware of any update having occurred.  I did check and notice that the extension was updated very recently, so perhaps VS2019 silently updated it for us this morning when we powered our systems up.  I've tried to confirm that, but I cannot find the history of Visual Studio Extension Updates, if such a thing exists.  BUT, FWIW, the VS2019 extension manager shows that we have version 1.3.0.

If there's anything I can do to help find out why the extension stopped working, let me know and I'll do my best.

**Comment by korypostma** [comment]
Ahh, crap man...  Microsoft really changed how they handled extensions in
VS 2022.  I can only recommend the following for now as I don't have time
to try and fix this, please get the VS 2017/2019 release here.  I think you
should manually uninstall first via extensions and then manually
double-click on this vsix to install it in VS2019.

https://github.com/korypostma/BlackSpace/releases

Hopefully, this version will still work.

**Comment by korypostma** [comment]
Can you also upload that ActivityLog.xml file?  It may be a simple change for me.

**Comment by nurbles** [comment]
Thanks for the tip on how to go back.  Here's the activity log xml/xsl files, too.  I hope they help.
[ActivityLog.zip](https://github.com/korypostma/BlackSpace/files/10735069/ActivityLog.zip)

[EDIT:  Your tip worked fine, too!  I turned off automatic update for BlackSpace to keep this from happening again.]

**Comment by korypostma** [comment]
OK, I think I know the problem, the plugin is expecting a newer version of the Microsoft.VisualStudio.Shell.15.0 file and my guess is that since you don't have VS 2022 installed on that machine as well, it will not have this newest version of the file.
```

  <entry>
    <record>1066</record>
    <time>2023/02/14 16:26:42.650</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>CreateInstance failed for package [BlackSpaceOptionsPackage]Source: &apos;mscorlib&apos; Description: Could not load file or assembly &apos;Microsoft.VisualStudio.Shell.15.0, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;System.IO.FileNotFoundException: Could not load file or assembly &apos;Microsoft.VisualStudio.Shell.15.0, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;File name: &apos;Microsoft.VisualStudio.Shell.15.0, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos;&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)&#x000D;&#x000A;   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)&#x000D;&#x000A;   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)&#x000D;&#x000A;&#x000D;&#x000A;WRN: Assembly binding logging is turned OFF.&#x000D;&#x000A;To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.&#x000D;&#x000A;Note: There is some performance penalty associated with assembly bind failure logging.&#x000D;&#x000A;To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;</description>
    <guid>{3F7DBE25-8DF3-454A-A340-31C8E0BA610E}</guid>
    <hr>80004005 - E_FAIL</hr>
    <errorinfo></errorinfo>
  </entry>
```

**Comment by nurbles** [comment]
Actually, we get the same error on two different machines.  One has VS2017 and VS2019 installed and the other one (where I captured the message image) has VS2019 and VS2022 installed.

**Comment by T-Troll** [comment]
Hello,

Have the same bug with 2019. 
Seems like the issue in online version (the way VS install it?), installing .vsix from here works well.

Update: Now VS warn me about this extension have an update, so online version is different.

**Comment by korypostma** [comment]
Wow, I'm so tired dealing with this issue.  You really cannot have one package for various versions and it seems going forward I'll need to make a new extension for each new version of Visual Studio.  Here is the link to the 2019 version, please test and let me know if it doesn't work.

[https://marketplace.visualstudio.com/items?itemName=vs-publisher-1248728.BlackSpace2019](url)
